# Generated by Django 4.0.5 on 2024-02-16 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=15)),
                ('label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('nick_name', models.CharField(max_length=100)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalpapp.number')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalpapp.number')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('join_date', models.DateField()),
                ('expire_date', models.DateField()),
                ('number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalpapp.number')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kalpapp.staff')),
            ],
        ),
    ]
